export interface Category {
  slug: string;
  name: string;
  eyebrow: string;
  blurb: string;
  cover: string;
}

export interface SpecRow {
  k: string;
  v: string;
}

export interface Product {
  slug: string;
  cat: string;
  name: string;
  sub: string;
  code: string;
  image: string;
  gallery: string[];
  tags: string[];
  lead: string;
  desc: string[];
  specs: SpecRow[];
  features: string[];
  applications: string[];
  categoryName?: string;
  categoryEyebrow?: string;
  fullName?: string;
}

export interface Customer {
  name: string;
  short: string;
  logo: string;
  sector: string;
}

const S = (k: string, v: string): SpecRow => ({ k, v });

export const categories: Category[] = [
  { slug: "tape-ct", name: "PVC Tape Insulated CTs", eyebrow: "Tape Insulated CT", blurb: "Economical PVC tape-insulated ring and rectangular current transformers for dry indoor LT metering and protection.", cover: "/assets/products/tape-ct/ring.webp" },
  { slug: "resin-ct", name: "Resin Cast CTs", eyebrow: "Resin Cast CT", blurb: "Epoxy resin-cast current transformers — ring, rectangular, bushing, WPL, summation, distribution and service types.", cover: "/assets/products/resin-ct/ring.webp" },
  { slug: "control", name: "Control Transformers", eyebrow: "Control · Machine Tool", blurb: "Single and three-phase control transformers — open, resin-cast and enclosure type — for machine tools and control circuits.", cover: "/assets/products/control/three-phase.jpg" },
  { slug: "auto", name: "Auto Transformers", eyebrow: "Auto · Chokes", blurb: "Fixed and variable auto transformers and matched input / output line chokes for drives and test benches.", cover: "/assets/products/auto/auto.jpg" },
  { slug: "pt", name: "Potential Transformers", eyebrow: "PT · Voltage", blurb: "Voltage (potential) transformers that step system voltage down to a safe, accurate reference for metering and protection.", cover: "/assets/products/pt/hea.webp" },
  { slug: "hv", name: "High Voltage Transformers", eyebrow: "HV · 11 kV / 33 kV", blurb: "Oil-cooled and resin-cast instrument transformers for sub-station metering and protection, rated up to 33 kV.", cover: "/assets/products/hv/11kv-ctpt.jpg" },
  { slug: "vibratory", name: "Vibratory Feeders", eyebrow: "Vibratory · Feeding", blurb: "Electromagnetic vibratory feeders for controlled, continuous feeding and conveying of bulk material in process plants.", cover: "/assets/products/vibratory/feeder.webp" },
  { slug: "epoxy", name: "Epoxy Insulators", eyebrow: "Epoxy · Insulation", blurb: "Resin-cast epoxy insulators and support bushings for indoor switchgear, bus-bars and panel assemblies.", cover: "/assets/products/epoxy/epoxy.webp" },
  { slug: "panels", name: "Electrical Panels", eyebrow: "LT / HT Panels", blurb: "EB HT & LT service, APFC, ACB, MV and distribution panels — built to your single-line and tested before dispatch.", cover: "/assets/products/panels/apfc.png" },
];

const rawProducts = [
  /* ============ 1 · PVC TAPE INSULATED CTS ============ */
  { slug: "tape-ring", cat: "tape-ct", name: "Ring Type Current Transformer", sub: "PVC Tape Insulated", code: "SE-TCT-RG", image: "/assets/products/tape-ct/ring.webp", gallery: ["/assets/products/tape-ct/ring.webp", "/assets/products/tape-ct/ring-2.webp"], tags: ["Window type", "Tape insulated", "IS 2705"], lead: "Economical window / ring-type CT insulated with layered PVC tape for dry indoor LT metering — the primary conductor simply passes through the ring.", desc: ["A ring (window) type current transformer insulated with layered PVC tape rather than cast resin, giving an economical option for clean, dry indoor LT panels.", "Light, compact and quick to fit, it is widely used for sub-metering and load monitoring inside distribution boards and control panels."], specs: [S("Type","Window / ring, tape insulated"),S("Rated primary current","50 – 2000 A"),S("Rated secondary current","5 A (1 A on request)"),S("Accuracy class","1.0 / 3.0"),S("Rated burden","5 – 10 VA"),S("System voltage","Up to 660 V"),S("Standard","IS 2705"),S("Mounting","Foot / bus-bar")], features: ["Layered PVC tape insulation","No primary winding — pass-through","Light & compact","Economical indoor option"], applications: ["Indoor LT sub-metering","Load & energy monitoring","OEM panel supply"] },
  { slug: "tape-rect", cat: "tape-ct", name: "Rectangular Type Current Transformer", sub: "PVC Tape Insulated", code: "SE-TCT-RECT", image: "/assets/products/tape-ct/rectangular.webp", gallery: ["/assets/products/tape-ct/rectangular.webp", "/assets/products/tape-ct/rectangular-2.png"], tags: ["Bus-bar window", "Tape insulated", "Economical"], lead: "Rectangular-window tape-insulated CT sized to slip over flat bus-bars in dry indoor LT panels and bus-ducts.", desc: ["A rectangular-window current transformer insulated with PVC tape and matched to standard flat bus-bar sections.", "Best suited to clean, dry indoor panels where the lower cost of tape insulation is preferred over resin casting."], specs: [S("Type","Rectangular window, tape insulated"),S("Rated primary current","100 – 3000 A"),S("Rated secondary current","5 A"),S("Accuracy class","1.0 / 3.0"),S("Rated burden","5 – 10 VA"),S("System voltage","Up to 660 V"),S("Standard","IS 2705"),S("Window","To suit bus-bar")], features: ["Rectangular bus-bar aperture","PVC tape insulation","Multiple window sizes","Cost-effective indoor CT"], applications: ["LT bus-bar metering","Distribution boards","Panel-builder supply"] },

  /* ============ 2 · RESIN CAST CTS ============ */
  { slug: "resin-ring", cat: "resin-ct", name: "Ring Type Current Transformer", sub: "Resin Cast", code: "SE-RCT-RG", image: "/assets/products/resin-ct/ring.webp", gallery: ["/assets/products/resin-ct/ring.webp","/assets/products/resin-ct/ring-2.png","/assets/products/resin-ct/ring-3.webp"], tags: ["Window type","Class 0.5","IS 2705"], lead: "Window / ring-type CT cast in epoxy resin — the primary conductor passes through the ring, making installation quick and clean.", desc: ["A resin-cast ring (window) type current transformer with no primary winding — the existing cable or bus-bar threads straight through the aperture.","Cast under vacuum in flame-retardant epoxy, with mounting feet and a clearly marked P1–P2 orientation for correct polarity."], specs: [S("Type","Window / ring, resin-cast"),S("Rated primary current","100 – 5000 A"),S("Rated secondary current","5 A (1 A on request)"),S("Accuracy class","0.5 / 1.0 / 3.0"),S("Rated burden","5 – 15 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705"),S("Mounting","Foot / bus-bar")], features: ["No primary winding — pass-through","Quick retrofit onto existing cable","Flame-retardant epoxy body","Marked P1–P2 polarity"], applications: ["LT panel metering","Sub-meter & energy monitoring","Earth-fault sensing"] },
  { slug: "resin-rect", cat: "resin-ct", name: "Rectangular Current Transformer", sub: "Resin Cast", code: "SE-RCT-RECT", image: "/assets/products/resin-ct/rectangular.png", gallery: ["/assets/products/resin-ct/rectangular.png"], tags: ["Bus-bar window","Class 0.5","IS 2705"], lead: "Rectangular-window resin-cast CT sized to slip over flat bus-bars in LT panels and bus-ducts.", desc: ["A resin-cast current transformer with a rectangular aperture matched to standard flat bus-bar sizes.","Available in a range of window sizes and primary ratings, with metering or protection accuracy as required."], specs: [S("Type","Rectangular window, resin-cast"),S("Rated primary current","200 – 5000 A"),S("Rated secondary current","5 A (1 A on request)"),S("Accuracy class","0.5 / 1.0"),S("Rated burden","5 – 15 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705"),S("Window","To suit bus-bar")], features: ["Rectangular bus-bar aperture","Multiple window sizes","Metering or protection cores","Panel foot mounting"], applications: ["LT bus-bar metering","Bus-duct & rising mains","Panel-builder OEM supply"] },
  { slug: "resin-bushing", cat: "resin-ct", name: "Bushing Type Current Transformer", sub: "Resin Cast", code: "SE-RCT-BSH", image: "/assets/products/resin-ct/bushing.webp", gallery: ["/assets/products/resin-ct/bushing.webp","/assets/products/resin-ct/bushing-2.png"], tags: ["Bushing","Slip-on","IS 2705"], lead: "Slip-on bushing CT designed to sit over a transformer or breaker bushing for primary current sensing.", desc: ["A resin-cast bushing-type current transformer that slips over an apparatus bushing to derive primary current without a separate primary connection.","Compact and robust, it suits restricted earth-fault and differential protection schemes."], specs: [S("Type","Bushing / slip-on, resin-cast"),S("Rated primary current","100 – 3000 A"),S("Rated secondary current","1 A / 5 A"),S("Accuracy class","5P10 / PS"),S("Rated burden","10 – 20 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705"),S("Mounting","Over bushing")], features: ["Slips over apparatus bushing","PS class for differential schemes","No primary termination","Rugged resin body"], applications: ["Transformer differential protection","Restricted earth-fault","Breaker current sensing"] },
  { slug: "resin-wpl", cat: "resin-ct", name: "WPL Current Transformer", sub: "Resin Cast", code: "SE-RCT-WPL", image: "/assets/products/resin-ct/wpl.webp", gallery: ["/assets/products/resin-ct/wpl.webp","/assets/products/resin-ct/wpl-2.png"], tags: ["Wound primary","Low ratio","IS 2705"], lead: "Wound-primary low-ratio CT cast in resin for accurate metering at small primary currents.", desc: ["A wound-primary-line (WPL) resin-cast current transformer for low primary ratings.","Terminals are provided for both primary and secondary, with the whole assembly cast in flame-retardant epoxy."], specs: [S("Type","Wound primary, resin-cast"),S("Rated primary current","5 – 100 A"),S("Rated secondary current","5 A (1 A on request)"),S("Accuracy class","0.5 / 1.0"),S("Rated burden","5 – 15 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705"),S("Mounting","Foot / DIN")], features: ["Multi-turn wound primary","Accurate at low currents","Primary & secondary terminals","Flame-retardant casting"], applications: ["Low-current sub-metering","Instrumentation circuits","Generator auxiliary metering"] },
  { slug: "resin-tneb", cat: "resin-ct", name: "TNEB Service Current Transformer", sub: "Resin Cast", code: "SE-RCT-TNEB", image: "/assets/products/resin-ct/tneb.png", gallery: ["/assets/products/resin-ct/tneb.png","/assets/products/resin-ct/tneb-2.webp","/assets/products/resin-ct/tneb-3.webp"], tags: ["Service CT","Sealable","Class 0.5"], lead: "Sealable service-connection CT built to electricity-board (TNEB) specification for LT consumer metering.", desc: ["A resin-cast current transformer made to electricity-board (TNEB) service specification for consumer LT metering.","Supplied in the ratios and accuracy class specified by the board, ready for service-connection panels."], specs: [S("Type","Service CT, resin-cast"),S("Rated primary current","100 – 800 A"),S("Rated secondary current","5 A"),S("Accuracy class","0.5"),S("Rated burden","5 – 10 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705 / board spec"),S("Terminals","Sealable, tamper-evident")], features: ["Made to electricity-board spec","Sealable, tamper-evident","Revenue-grade accuracy","Service-panel ready"], applications: ["LT consumer service metering","Board-approved service panels","Revenue energy metering"] },
  { slug: "resin-distribution", cat: "resin-ct", name: "Distribution Transformer CT", sub: "Resin Cast", code: "SE-RCT-DTC", image: "/assets/products/resin-ct/distribution.webp", gallery: ["/assets/products/resin-ct/distribution.webp"], tags: ["Distribution","LT metering","IS 2705"], lead: "Resin-cast CT dimensioned for distribution-transformer LT terminals, for feeder metering and protection at the transformer.", desc: ["A resin-cast current transformer sized for the LT side of a distribution transformer.","Robust foot mounting and a void-free cast body give dependable performance in distribution sub-stations."], specs: [S("Type","Distribution CT, resin-cast"),S("Rated primary current","200 – 3000 A"),S("Rated secondary current","5 A (1 A on request)"),S("Accuracy class","0.5 / 5P10"),S("Rated burden","10 – 20 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705"),S("Mounting","Foot")], features: ["Sized for distribution LT terminals","Metering & protection cores","Void-free vacuum casting","Rugged foot mounting"], applications: ["Distribution transformer metering","LT feeder protection","Packaged sub-stations"] },
  { slug: "resin-summation", cat: "resin-ct", name: "Summation Current Transformer", sub: "Resin Cast", code: "SE-RCT-SUM", image: "/assets/products/resin-ct/summation.webp", gallery: ["/assets/products/resin-ct/summation.webp"], tags: ["Summation","Multi-input","Metering"], lead: "Summation CT that adds the currents of several feeders into a single proportional output for combined metering.", desc: ["A summation current transformer combines the secondary currents of two or more feeder CTs and delivers a single output proportional to their sum.","Cast in epoxy with multiple primary inputs and one secondary, configured to the required summation ratio."], specs: [S("Type","Summation CT, resin-cast"),S("Inputs","2 – 5 feeders (to order)"),S("Input / output","5 A inputs : 5 A output"),S("Accuracy class","1.0"),S("Rated burden","5 – 15 VA"),S("System voltage","Up to 1.1 kV"),S("Standard","IS 2705"),S("Mounting","Foot / panel")], features: ["Sums multiple feeder currents","Single proportional output","Configurable summation ratio","Epoxy cast body"], applications: ["Combined / total metering","Multi-incomer summation","Load aggregation"] },

  /* ============ 3 · CONTROL TRANSFORMERS ============ */
  { slug: "control-single", cat: "control", name: "Single Phase Control Transformer", sub: "Open Type", code: "SE-CTL-1PH", image: "/assets/products/control/single-phase.png", gallery: ["/assets/products/control/single-phase.png","/assets/products/control/single-phase-b.webp","/assets/products/control/single-phase-2.jpg"], tags: ["1-Ph","Step-down","IEC 61558"], lead: "Single-phase control transformer that delivers a stable, isolated control-voltage supply for machine and panel circuits.", desc: ["A single-phase double-wound control transformer providing an isolated, regulated control supply — typically 415 V to 110 V or 230 V — for contactor coils.","Wound on a low-loss CRGO core with class-rated insulation and varnish impregnation for thermal and mechanical robustness."], specs: [S("Type","Single-phase, double wound"),S("Rated power","63 VA – 5 kVA"),S("Primary voltage","240 / 415 V"),S("Secondary voltage","12 – 240 V (to order)"),S("Insulation class","Class B / F / H"),S("Frequency","50 Hz"),S("Regulation","≤ 5 %"),S("Standard","IS 1180 / IEC 61558")], features: ["Isolated double-wound design","Low-loss CRGO core","Varnish impregnated","Custom tappings to order"], applications: ["Machine-tool control circuits","Contactor & relay supply","Panel control voltage"] },
  { slug: "control-three", cat: "control", name: "Three Phase Control Transformer", sub: "Open Type", code: "SE-CTL-3PH", image: "/assets/products/control/three-phase.jpg", gallery: ["/assets/products/control/three-phase.jpg","/assets/products/control/three-phase-b.webp"], tags: ["3-Ph","Step-down","CRGO"], lead: "Three-phase control and isolation transformer for higher-power control and auxiliary supplies.", desc: ["A three-phase double-wound transformer for control, isolation and auxiliary-supply duties.","Built on a stacked CRGO core with class-rated insulation, it runs cool and quiet under continuous load."], specs: [S("Type","Three-phase, double wound"),S("Rated power","1 – 25 kVA"),S("Primary voltage","415 V"),S("Secondary voltage","110 – 415 V (to order)"),S("Vector group","Dyn11 / Yyn0"),S("Insulation class","Class B / F / H"),S("Frequency","50 Hz"),S("Standard","IS 1180 / IEC 61558")], features: ["Three-phase isolation","Standard & custom vector groups","Stacked CRGO core","Continuous-rated"], applications: ["Auxiliary power supplies","Machine & process control","Voltage matching / isolation"] },
  { slug: "control-enclosure", cat: "control", name: "Enclosure Type Control Transformer", sub: "Sheet-Steel Enclosed", code: "SE-CTL-ENC", image: "/assets/products/control/enclosure.gif", gallery: ["/assets/products/control/enclosure.gif","/assets/products/control/enclosure-2.png","/assets/products/control/enclosure-3.webp","/assets/products/control/enclosure-4.webp"], tags: ["Enclosed","IP rated","Terminals"], lead: "Control transformer housed in a ventilated sheet-steel enclosure with terminal block — ready to wall- or floor-mount.", desc: ["The same proven control transformer core supplied inside a powder-coated sheet-steel enclosure with cable glands and a terminal block.","Ventilation louvres keep the winding cool while the enclosure protects against accidental contact and ingress."], specs: [S("Type","Enclosed control transformer"),S("Rated power","1 – 15 kVA"),S("Enclosure","Powder-coated CRCA steel"),S("Protection","IP23 / IP43 (to order)"),S("Primary voltage","240 / 415 V"),S("Secondary voltage","To order"),S("Insulation class","Class B / F"),S("Standard","IS 1180 / IEC 61558")], features: ["Ventilated steel enclosure","Cable glands & terminal block","IP-rated protection","Wall / floor mounting"], applications: ["Stand-alone control supply","Workshop & plant areas","Retrofit installations"] },
  { slug: "control-resin", cat: "control", name: "Resin Cast Control Transformer", sub: "Encapsulated", code: "SE-CTL-RC", image: "/assets/products/control/resin-cast.webp", gallery: ["/assets/products/control/resin-cast.webp"], tags: ["Encapsulated","Robust","Maintenance-free"], lead: "Fully encapsulated control transformer cast in resin for harsh, humid or vibration-prone environments.", desc: ["A control transformer with its core and windings fully encapsulated in epoxy resin, sealing out moisture, dust and contaminants.","Ideal where the transformer is exposed to humidity, condensation or continuous vibration that would degrade an open-wound unit."], specs: [S("Type","Resin-encapsulated control transformer"),S("Rated power","63 VA – 5 kVA"),S("Primary voltage","240 / 415 V"),S("Secondary voltage","12 – 240 V (to order)"),S("Protection","Sealed, IP65 body"),S("Insulation class","Class F / H"),S("Frequency","50 Hz"),S("Standard","IEC 61558")], features: ["Fully encapsulated in epoxy","Moisture & dust sealed","Vibration damped","Maintenance-free"], applications: ["Humid & marine environments","Vibration-prone machinery","Outdoor-adjacent enclosures"] },

  /* ============ 4 · AUTO TRANSFORMERS ============ */
  { slug: "auto-transformer", cat: "auto", name: "Auto Transformer", sub: "Single / Three Phase", code: "SE-AT", image: "/assets/products/auto/auto.jpg", gallery: ["/assets/products/auto/auto.jpg"], tags: ["Step up/down","Compact","Efficient"], lead: "Single-winding auto transformer for economical voltage step-up or step-down where galvanic isolation is not required.", desc: ["An auto transformer uses a single tapped winding to shift voltage up or down — at lower cost, size and loss than an equivalent double-wound unit.","Available single- or three-phase with fixed tappings to match imported machinery and supply-voltage correction."], specs: [S("Type","Auto transformer (1-Ph / 3-Ph)"),S("Rated power","1 – 100 kVA"),S("Voltage range","To order (e.g. 415 ↔ 380 V)"),S("Tappings","Fixed, multi-tap"),S("Insulation class","Class B / F"),S("Frequency","50 Hz"),S("Cooling","AN (dry)"),S("Standard","IS 2026 / IEC 60076")], features: ["Single-winding efficiency","Compact & low-loss","Fixed multi-tap","Voltage correction ready"], applications: ["Imported machine voltage matching","Supply voltage correction","Motor starting (compensator)"] },
  { slug: "auto-variable", cat: "auto", name: "Variable Auto Transformer", sub: "Dimmerstat", code: "SE-VAT", image: "/assets/products/auto/variable.webp", gallery: ["/assets/products/auto/variable.webp","/assets/products/auto/variable-2.webp"], tags: ["0–100 %","Continuous","Carbon brush"], lead: "Continuously variable auto transformer (variac) giving smooth, stepless control of output voltage from zero to full.", desc: ["A variable auto transformer — a variac / dimmerstat — with a carbon brush running over an exposed toroidal winding.","Available in portable single-phase units and ganged three-phase assemblies, open or enclosed with a voltmeter."], specs: [S("Type","Continuously variable auto transformer"),S("Configuration","1-Ph / 3-Ph ganged"),S("Output range","0 – 270 V (per phase)"),S("Current rating","0.5 – 100 A"),S("Control","Carbon brush, stepless"),S("Frequency","50 Hz"),S("Mounting","Portable / panel"),S("Standard","IS 5142")], features: ["Stepless 0–100 % output","Carbon-brush wiper","Portable or panel mount","Optional voltmeter"], applications: ["Test & laboratory benches","Process heating control","Equipment soak testing"] },
  { slug: "auto-choke", cat: "auto", name: "Input / Output Choke", sub: "Line Reactor", code: "SE-CHK", image: "/assets/products/auto/choke.jpg", gallery: ["/assets/products/auto/choke.jpg","/assets/products/auto/choke-2.webp"], tags: ["Line reactor","dv/dt","Drives"], lead: "Matched line reactors that protect variable-frequency drives and smooth their output to the motor.", desc: ["Input and output chokes (line reactors) for variable-frequency drives.","Wound on gapped cores and sized to the drive rating, supplied open or in a terminal enclosure."], specs: [S("Type","Line reactor / choke"),S("Service","VFD input & output"),S("Impedance","2 % / 3 % / 5 %"),S("Current rating","To drive rating"),S("Insulation class","Class F / H"),S("Frequency","50 Hz"),S("Mounting","Open / enclosed"),S("Standard","IEC 60076-6")], features: ["Harmonic & transient reduction","dv/dt limiting on output","Sized to drive rating","Gapped low-loss core"], applications: ["VFD / inverter supplies","Long motor cable runs","Harmonic mitigation"] },

  /* ============ 5 · POTENTIAL TRANSFORMERS ============ */
  { slug: "pt-hea", cat: "pt", name: "HEA Potential Transformer", sub: "Voltage Transformer", code: "SE-PT-HEA", image: "/assets/products/pt/hea.webp", gallery: ["/assets/products/pt/hea.webp"], tags: ["Voltage ref","Class 0.5","IS 3156"], lead: "Potential (voltage) transformer that steps system voltage down to a safe, accurate reference for metering and protection circuits.", desc: ["A potential transformer provides an accurate, isolated low-voltage replica of the system voltage — typically 110 V — for energy meters, voltmeters and protective relays.","Wound and finished to deliver dependable ratio and phase accuracy across its rated burden range."], specs: [S("Type","Potential / voltage transformer"),S("Rated voltage ratio","to order : 110 V"),S("Accuracy class","0.5 / 3P"),S("Rated burden","50 – 200 VA"),S("Insulation","Class B / F"),S("Frequency","50 Hz"),S("Service","Indoor"),S("Standard","IS 3156 / IEC 61869")], features: ["Accurate, isolated voltage reference","Electrostatic inter-winding screen","Stable across burden range","Metering & protection windings"], applications: ["Panel metering & indication","Protective-relay reference","Control & synchronising circuits"] },

  /* ============ 6 · HIGH VOLTAGE TRANSFORMERS ============ */
  { slug: "hv-11kv-ct", cat: "hv", name: "11 kV Single-Phase CT", sub: "Oil Cooled", code: "SE-HV-CT-11", image: "/assets/products/hv/11kv-ct.jpg", gallery: ["/assets/products/hv/11kv-ct.jpg"], tags: ["11 kV","Class 0.5","IS 2705"], lead: "Single-phase, oil-immersed current transformer for outdoor 11 kV metering and protection on utility feeders.", desc: ["An oil-cooled single-phase current transformer built for outdoor 11 kV sub-station duty, housed in a hermetically sealed steel tank with porcelain bushings.","Cores are graded for separate metering and protection secondaries so a single unit can drive both an energy meter and protective relays."], specs: [S("Type","Single-phase, oil-immersed CT"),S("Highest system voltage","12 kV"),S("Rated primary current","5 – 1200 A"),S("Rated secondary current","1 A / 5 A"),S("Accuracy class","0.5 / 5P10"),S("Rated burden","15 – 30 VA"),S("Insulation level","28 / 75 kV"),S("Standard","IS 2705")], features: ["Hermetically sealed steel tank","Separate metering & protection cores","Porcelain primary bushings","Routine ratio & burden tested"], applications: ["Outdoor 11 kV sub-station metering","Feeder over-current protection","HT service connections"] },
  { slug: "hv-11kv-pt", cat: "hv", name: "11 kV Single-Phase PT", sub: "Oil Cooled", code: "SE-HV-PT-11", image: "/assets/products/hv/11kv-pt.png", gallery: ["/assets/products/hv/11kv-pt.png"], tags: ["11 kV","Class 0.5","IS 3156"], lead: "Oil-cooled single-phase voltage transformer that steps 11 kV down to a safe 110 V reference for metering and relay circuits.", desc: ["A single-phase oil-immersed potential transformer providing an accurate, isolated 110 V secondary for revenue metering and protection.","Supplied with porcelain bushings and a sealed tank for outdoor mounting."], specs: [S("Type","Single-phase, oil-immersed PT"),S("Highest system voltage","12 kV"),S("Rated voltage ratio","11000 / √3 : 110 / √3 V"),S("Accuracy class","0.5 / 3P"),S("Rated burden","50 – 100 VA"),S("Insulation level","28 / 75 kV"),S("Frequency","50 Hz"),S("Standard","IS 3156")], features: ["Electrostatic inter-winding screen","Sealed outdoor tank","Stable reference output","Routine ratio & HV tested"], applications: ["HT revenue metering","Synchronising & relay reference","Bus voltage indication"] },
  { slug: "hv-11kv-ctpt", cat: "hv", name: "11 kV CTPT Metering Unit", sub: "Oil Cooled", code: "SE-HV-CTPT-11", image: "/assets/products/hv/11kv-ctpt.jpg", gallery: ["/assets/products/hv/11kv-ctpt.jpg"], tags: ["11 kV","3-Ph","Combined Metering"], lead: "Combined current and voltage transformer unit in a single oil-filled tank — the complete HT metering package for service connections.", desc: ["A combined CTPT metering set that brings three-phase current and voltage transformers together in one oil-immersed tank.","Factory-wired to a sealable terminal box, the unit arrives ready to connect to the utility meter."], specs: [S("Type","Combined CT + PT, oil-immersed"),S("Highest system voltage","12 kV"),S("CT ratio","to order, 10 – 600 A"),S("PT ratio","11000 / √3 : 110 / √3 V"),S("Accuracy class","0.5 (metering)"),S("Insulation level","28 / 75 kV"),S("Standard","IS 2705 / IS 3156"),S("Cooling","ONAN (oil)")], features: ["CT + PT in one tank","Sealable metering terminal box","Factory wired & calibrated","Reduced site installation"], applications: ["Industrial HT service metering","Utility boundary metering","Outdoor pole / plinth mounting"] },
  { slug: "hv-33kv-ct", cat: "hv", name: "33 kV Single-Phase CT", sub: "Oil Cooled", code: "SE-HV-CT-33", image: "/assets/products/hv/33kv-ct.webp", gallery: ["/assets/products/hv/33kv-ct.webp"], tags: ["33 kV","Class 0.2S","IS 2705"], lead: "Heavy-duty 33 kV oil-immersed current transformer for grid sub-station metering and protection.", desc: ["Our largest instrument transformer class — a 33 kV single-phase oil-cooled CT with long-creepage porcelain bushings for outdoor grid sub-stations.","High-accuracy 0.2S metering cores are available for inter-utility energy accounting."], specs: [S("Type","Single-phase, oil-immersed CT"),S("Highest system voltage","36 kV"),S("Rated primary current","10 – 1200 A"),S("Rated secondary current","1 A / 5 A"),S("Accuracy class","0.2S / 5P20"),S("Rated burden","15 – 30 VA"),S("Insulation level","70 / 170 kV"),S("Standard","IS 2705")], features: ["Long-creepage porcelain bushings","0.2S revenue-grade cores","36 kV sealed tank","Type & routine tested"], applications: ["33 kV grid sub-stations","Inter-utility energy metering","EHV feeder protection"] },
  { slug: "hv-resin-pt", cat: "hv", name: "11 kV Three-Phase PT", sub: "Resin Cast", code: "SE-HV-RPT-11", image: "/assets/products/hv/resin-pt.jpeg", gallery: ["/assets/products/hv/resin-pt.jpeg","/assets/products/hv/resin-pt-2.jpeg"], tags: ["11 kV","3-Ph","Resin Cast"], lead: "Dry-type, epoxy resin-cast three-phase voltage transformer for indoor 11 kV switchboards — no oil, no maintenance.", desc: ["A maintenance-free, dry-type three-phase PT cast in epoxy resin under vacuum.","The cast body is self-extinguishing and track-resistant, suited to clean indoor switchroom environments."], specs: [S("Type","Three-phase, epoxy resin-cast PT"),S("Highest system voltage","12 kV"),S("Rated voltage ratio","11000 / √3 : 110 / √3 V"),S("Accuracy class","0.5 / 3P"),S("Rated burden","50 – 100 VA"),S("Insulation level","28 / 75 kV"),S("Standard","IS 3156"),S("Cooling","Dry, natural air")], features: ["Oil-free, maintenance-free","Vacuum cast epoxy body","Self-extinguishing insulation","Compact indoor footprint"], applications: ["Indoor 11 kV metering cubicles","Protection & synchronising","Panel-mounted voltage reference"] },
  { slug: "hv-resin-ct", cat: "hv", name: "11 kV Current Transformer", sub: "Resin Cast", code: "SE-HV-RCT-11", image: "/assets/products/hv/resin-ct.jpeg", gallery: ["/assets/products/hv/resin-ct.jpeg","/assets/products/hv/resin-ct-2.jpeg"], tags: ["11 kV","Resin Cast","5P10"], lead: "Dry-type epoxy resin-cast 11 kV current transformer for indoor switchgear — clean, compact and oil-free.", desc: ["An indoor 11 kV current transformer cast in epoxy resin, combining metering and protection cores in a compact, oil-free body.","Designed to mount directly in indoor switchboard cubicles with bus-bar or cable primary connections."], specs: [S("Type","Epoxy resin-cast CT"),S("Highest system voltage","12 kV"),S("Rated primary current","50 – 1250 A"),S("Rated secondary current","1 A / 5 A"),S("Accuracy class","0.5 / 5P10"),S("Rated burden","15 – 30 VA"),S("Insulation level","28 / 75 kV"),S("Standard","IS 2705")], features: ["Void-free vacuum casting","Dual metering / protection cores","Bus-bar or cable primary","Oil-free indoor design"], applications: ["Indoor 11 kV switchboards","Metering & feeder protection","Compact panel cubicles"] },

  /* ============ 7 · VIBRATORY FEEDERS ============ */
  { slug: "vibratory-feeder", cat: "vibratory", name: "Vibratory Feeder", sub: "Electromagnetic", code: "SE-VF", image: "/assets/products/vibratory/feeder.webp", gallery: ["/assets/products/vibratory/feeder.webp"], tags: ["Electromagnetic","Controlled feed","Bulk handling"], lead: "Electromagnetic vibratory feeder for controlled, continuous feeding and conveying of bulk material into process equipment.", desc: ["An electromagnetic vibratory feeder uses a controlled vibrating tray to move granular and bulk material at a precise, adjustable rate.","The feed rate is set electronically through a controller, giving smooth start/stop and accurate dosing."], specs: [S("Type","Electromagnetic vibratory feeder"),S("Drive","Electromagnetic, no rotating parts"),S("Feed rate","Adjustable via controller"),S("Tray","MS / SS, to material"),S("Supply","230 V, 50 Hz (controller)"),S("Control","Variable, stepless"),S("Duty","Continuous"),S("Mounting","Suspended / base")], features: ["Stepless electronic feed control","No rotating wear parts","Smooth start / stop","Rugged continuous-duty build"], applications: ["Crusher & weigher feeding","Furnace & process dosing","Packing & batching lines"] },

  /* ============ 8 · EPOXY INSULATORS ============ */
  { slug: "epoxy-insulator", cat: "epoxy", name: "Epoxy Cast Insulator", sub: "Support / Standoff", code: "SE-INS-EP", image: "/assets/products/epoxy/epoxy.webp", gallery: ["/assets/products/epoxy/epoxy.webp","/assets/products/epoxy/epoxy-2.webp","/assets/products/epoxy/epoxy-3.webp","/assets/products/epoxy/epoxy-4.webp"], tags: ["Support","Track-resistant","Indoor"], lead: "Cast epoxy support and standoff insulators that carry and space bus-bars and live parts inside indoor LT and MV switchgear.", desc: ["Resin-cast epoxy insulators that support and space bus-bars and live parts inside indoor switchgear and panels.","Available in a range of heights and fixing patterns, with brass or galvanised inserts moulded in for secure mechanical fixing."], specs: [S("Type","Cast epoxy support / standoff insulator"),S("System voltage","Up to 12 kV"),S("Material","Cycloaliphatic epoxy"),S("Inserts","Brass / GI, moulded-in"),S("Height range","20 – 250 mm"),S("Mechanical load","To order"),S("Service","Indoor"),S("Standard","IS 2544")], features: ["Track & erosion resistant","Moulded-in metal inserts","High mechanical strength","Wide range of sizes"], applications: ["Bus-bar support","Switchgear assemblies","Isolator & link mounting"] },

  /* ============ 9 · ELECTRICAL PANELS ============ */
  { slug: "panel-htct-outdoor", cat: "panels", name: "2-Compartment HTCT Metering Panel", sub: "Outdoor Type", code: "SE-PNL-HTCT", image: "/assets/products/panels/htct-metering-outdoor.jpg", gallery: ["/assets/products/panels/htct-metering-outdoor.jpg"], tags: ["HT metering","Outdoor","Sealable"], lead: "Two-compartment outdoor HT metering panel housing the CTs/PTs and the sealable utility meter for HT service connections.", desc: ["A weatherproof two-compartment HT metering panel for outdoor service connections — one compartment for instrument transformers, one sealable for the utility meter.","Built to electricity-board metering requirements with gasketed doors, canopy and a powder-coated weatherproof body."], specs: [S("Type","HT CT metering panel, 2-compartment"),S("Service voltage","11 kV / 33 kV"),S("Construction","Outdoor, weatherproof"),S("Protection","IP54 / IP55"),S("Metering","Sealable, board approved"),S("Termination","Test terminal block"),S("Finish","Powder-coated CRCA"),S("Standard","Board metering spec")], features: ["Separate metering compartment","Sealable, board approved","Weatherproof gasketed body","Test terminal block"], applications: ["HT service-connection metering","Utility boundary metering","Outdoor plinth mounting"] },
  { slug: "panel-ltct-3-indoor", cat: "panels", name: "3-Compartment LTCT Service Panel", sub: "Indoor Type", code: "SE-PNL-LTCT3-IN", image: "/assets/products/panels/ltct-3-indoor.webp", gallery: ["/assets/products/panels/ltct-3-indoor.webp","/assets/products/panels/ltct-3-indoor-2.webp"], tags: ["LT service","Indoor","Sealable"], lead: "Three-compartment indoor LT service panel combining incomer, CT metering and outgoing in one board-compliant cabinet.", desc: ["A three-compartment indoor LT service panel arranged for incoming supply, sealable CT metering and outgoing distribution.","Fully wired with service CTs, sealable meter compartment and an isolating switch / MCCB to the board's requirement."], specs: [S("Type","LT CT service panel, 3-compartment"),S("Rated voltage","415 V, 3-Ph, 50 Hz"),S("Rated current","100 – 800 A"),S("Construction","Indoor, floor-standing"),S("Protection","IP42 / IP54"),S("Metering","Sealable, board approved"),S("Incomer","Switch / MCCB"),S("Standard","IS 8623 / board spec")], features: ["Three-compartment layout","Sealable CT metering","Board-approved build","Switch / MCCB incomer"], applications: ["Indoor LT service metering","Commercial connections","Board-compliant service cut-outs"] },
  { slug: "panel-ltct-3-outdoor", cat: "panels", name: "3-Compartment LTCT Service Panel", sub: "Outdoor Type", code: "SE-PNL-LTCT3-OUT", image: "/assets/products/panels/ltct-3-outdoor.jpeg", gallery: ["/assets/products/panels/ltct-3-outdoor.jpeg"], tags: ["LT service","Outdoor","Weatherproof"], lead: "Weatherproof outdoor version of the LT CT service panel for pavement and plinth-mounted service connections.", desc: ["The outdoor variant of our LT CT service panel, in a weatherproof canopied enclosure for kerb, plinth or pole-adjacent mounting.","Sun canopy, drip-proof louvres and a powder-coated weather finish keep the metering dry and sealed outdoors."], specs: [S("Type","LT CT service panel, outdoor"),S("Rated voltage","415 V, 3-Ph, 50 Hz"),S("Rated current","100 – 800 A"),S("Construction","Outdoor, weatherproof"),S("Protection","IP54 / IP55"),S("Metering","Sealable, board approved"),S("Canopy","Sun / rain canopy"),S("Standard","IS 8623 / board spec")], features: ["Weatherproof canopied body","Sealable CT metering","Drip-proof louvres","Plinth / kerb mounting"], applications: ["Outdoor LT service metering","Street & plinth connections","Board-compliant cut-outs"] },
  { slug: "panel-ltct-5-indoor", cat: "panels", name: "5-Compartment LTCT Service Panel", sub: "Indoor Type", code: "SE-PNL-LTCT5-IN", image: "/assets/products/panels/ltct-5-indoor.webp", gallery: ["/assets/products/panels/ltct-5-indoor.webp"], tags: ["LT service","5-compartment","Indoor"], lead: "Five-compartment indoor LT service panel for larger service connections needing separate metering, incomer and multiple outgoings.", desc: ["A five-compartment indoor LT service panel for higher-rated service connections.","Engineered to the board's metering requirement with a rated bus-bar system and clearly compartmentalised construction."], specs: [S("Type","LT CT service panel, 5-compartment"),S("Rated voltage","415 V, 3-Ph, 50 Hz"),S("Rated current","200 – 1600 A"),S("Construction","Indoor, floor-standing"),S("Protection","IP42 / IP54"),S("Metering","Sealable, board approved"),S("Outgoings","Multiple MCCB ways"),S("Standard","IS 8623 / board spec")], features: ["Five-compartment layout","Sealable CT metering","Multiple outgoing ways","Higher-rated service duty"], applications: ["Large LT service metering","Commercial & industrial connections","Multi-feeder distribution"] },
  { slug: "panel-acb", cat: "panels", name: "ACB Panel", sub: "Outdoor Type", code: "SE-PNL-ACB", image: "/assets/products/panels/acb-outdoor.avif", gallery: ["/assets/products/panels/acb-outdoor.avif"], tags: ["ACB","Main incomer","Outdoor"], lead: "Air-circuit-breaker panel forming the protected main incomer / bus-coupler for LT distribution.", desc: ["An ACB panel housing a draw-out air circuit breaker as the main incomer or bus-coupler for an LT system.","Compartmentalised construction separates the breaker, bus-bar and cable zones."], specs: [S("Type","ACB incomer / bus-coupler panel"),S("Rated voltage","415 V, 3-Ph, 50 Hz"),S("Rated current","630 – 4000 A"),S("Breaking capacity","50 / 65 kA"),S("Breaker","Draw-out ACB"),S("Protection","Microprocessor release"),S("Form","Form 3b / 4 (to order)"),S("Standard","IS / IEC 61439")], features: ["Draw-out ACB","Microprocessor releases","Compartmentalised form","Indoor / outdoor build"], applications: ["LT main incomer","Bus-coupler / tie","Generator / transformer feeders"] },
  { slug: "panel-apfc", cat: "panels", name: "APFC Panel", sub: "Automatic Power Factor Correction", code: "SE-PNL-APFC", image: "/assets/products/panels/apfc.png", gallery: ["/assets/products/panels/apfc.png"], tags: ["Power factor","Auto stages","LT"], lead: "Automatic power-factor-correction panel that switches capacitor stages to hold a target power factor and cut demand charges.", desc: ["An APFC panel continuously measures plant power factor and switches capacitor banks in and out through a microprocessor relay.","Built with detuned reactors where harmonics are present, MCCB / contactor switching and a clear front mimic."], specs: [S("Type","Automatic PF correction panel"),S("Rated voltage","415 V, 3-Ph, 50 Hz"),S("Capacitor rating","25 – 600 kVAr"),S("Stages","6 / 8 / 12 step"),S("Switching","Contactor / thyristor"),S("Detuning","7 % reactor (optional)"),S("Enclosure","Floor-standing CRCA"),S("Standard","IS 8623 / IEC 61439")], features: ["Microprocessor PF relay","Stepwise capacitor switching","Optional detuned reactors","Demand-charge reduction"], applications: ["Industrial PF improvement","Demand-charge management","Harmonic-rich plants (detuned)"] },
  { slug: "panel-lt-distribution", cat: "panels", name: "LT Distribution Panel", sub: "Indoor Type", code: "SE-PNL-LTDB", image: "/assets/products/panels/lt-distribution-indoor.webp", gallery: ["/assets/products/panels/lt-distribution-indoor.webp"], tags: ["Distribution","MCCB","Indoor"], lead: "Floor-standing LT distribution board that takes the main incomer and feeds multiple MCCB / switch-fuse outgoings.", desc: ["An LT distribution panel built around a rated bus-bar system, taking the incoming supply and distributing it to numerous outgoing feeders.","Designed to the required form of separation with engineered bus-bar bracing for the specified fault level."], specs: [S("Type","LT distribution board"),S("Rated voltage","415 V, 3-Ph, 50 Hz"),S("Bus-bar rating","Up to 4000 A"),S("Fault level","50 / 65 kA for 1 s"),S("Outgoings","MCCB / switch-fuse"),S("Form","Form 2 / 3b / 4"),S("Protection","IP42 / IP54"),S("Standard","IS 8623 / IEC 61439")], features: ["Engineered bus-bar system","MCCB / switch-fuse outgoings","Selectable form of separation","Braced for fault level"], applications: ["Plant LT distribution","Sub-distribution boards","Motor & lighting feeders"] },
  { slug: "panel-mv", cat: "panels", name: "MV Panel", sub: "Indoor Type", code: "SE-PNL-MV", image: "/assets/products/panels/mv-indoor.jpg", gallery: ["/assets/products/panels/mv-indoor.jpg"], tags: ["MV","Switchgear","Indoor"], lead: "Medium-voltage switchgear panel housing VCB and instrument transformers for 11 kV / 33 kV distribution.", desc: ["A medium-voltage panel built around a vacuum circuit breaker with integral CTs, PTs and protection relays for 11 kV or 33 kV switching.","Interlocks, earthing facilities and a clear front mimic are provided to the single-line diagram and protection scheme."], specs: [S("Type","MV switchgear panel (VCB)"),S("System voltage","11 kV / 33 kV"),S("Rated current","630 – 2500 A"),S("Breaking capacity","25 / 31.5 kA"),S("Breaker","Vacuum circuit breaker"),S("Protection","Numerical relay"),S("Interlocks","Mechanical & electrical"),S("Standard","IS / IEC 62271")], features: ["Vacuum circuit breaker","Integral CT / PT & relays","Safety interlocks & earthing","Built to single-line"], applications: ["11 / 33 kV distribution","Incomer & feeder switching","Sub-station automation"] },
  { slug: "panel-socket", cat: "panels", name: "Power Socket Panel", sub: "1-Ph & 3-Ph", code: "SE-PNL-SOCK", image: "/assets/products/panels/power-socket.jpg", gallery: ["/assets/products/panels/power-socket.jpg"], tags: ["Socket outlets","Industrial","RCD"], lead: "Industrial socket-outlet panel delivering protected single- and three-phase supplies to plant and welding points.", desc: ["A power socket panel providing a cluster of protected industrial socket outlets — single- and three-phase — for workshops, welding bays and construction supplies.","Robust metal-clad construction with interlocked industrial plugs and tops keeps temporary and tool supplies safe."], specs: [S("Type","Industrial socket-outlet panel"),S("Rated voltage","240 V / 415 V, 50 Hz"),S("Outlets","16 / 32 / 63 A industrial"),S("Protection","MCB / RCBO per outlet"),S("Interlock","Switched-interlocked sockets"),S("Enclosure","Metal-clad / FRP"),S("Protection class","IP54 / IP65"),S("Standard","IS / IEC 60309")], features: ["Single & three-phase outlets","RCD protection per outlet","Switched-interlocked sockets","Robust metal-clad body"], applications: ["Workshop & welding bays","Construction power supply","Maintenance tool points"] },
  { slug: "panel-fuse-carrier", cat: "panels", name: "Fuse Carrier Aerial Plate", sub: "Service Fitting", code: "SE-PNL-FCAP", image: "/assets/products/panels/fuse-carrier.webp", gallery: ["/assets/products/panels/fuse-carrier.webp"], tags: ["Service fuse","Cut-out","LT"], lead: "Fuse carrier and aerial plate assembly forming the protected LT service cut-out at the consumer terminal.", desc: ["A fuse carrier mounted on an aerial / service plate, forming the LT cut-out where the service cable terminates at the consumer end.","Moulded insulating base, robust contacts and a clearly rated HRC fuse carrier make for a safe, replaceable service termination."], specs: [S("Type","Service fuse carrier & plate"),S("Rated voltage","240 / 415 V, 50 Hz"),S("Rated current","63 – 200 A"),S("Fuse","HRC cartridge"),S("Base","Moulded insulating"),S("Mounting","Aerial / service plate"),S("Service","LT consumer cut-out"),S("Standard","IS 13703")], features: ["HRC service fuse protection","Moulded insulating base","Replaceable fuse carrier","Aerial plate mounting"], applications: ["LT service cut-out","Consumer terminal protection","Service-connection boards"] },
];

const catMap = Object.fromEntries(categories.map(c => [c.slug, c]));

export const products: Product[] = rawProducts.map(p => ({
  ...p,
  gallery: p.gallery ?? [p.image],
  categoryName: catMap[p.cat]?.name ?? "",
  categoryEyebrow: catMap[p.cat]?.eyebrow ?? "",
  fullName: p.sub ? `${p.name} · ${p.sub}` : p.name,
}));

export const customers: Customer[] = [
  { name: "Tamil Nadu Electricity Board (TNEB)", short: "TNEB", logo: "/assets/customers/tneb.jpg", sector: "State Power Utility" },
  { name: "TANGEDCO", short: "TANGEDCO", logo: "/assets/customers/tangedco.avif", sector: "Power Utility" },
  { name: "TANTRANSCO", short: "TANTRANSCO", logo: "/assets/customers/tantransco.png", sector: "Power Transmission" },
  { name: "Airports Authority of India", short: "AAI", logo: "/assets/customers/aai.png", sector: "Infrastructure" },
  { name: "GAIL (India) Limited", short: "GAIL", logo: "/assets/customers/gail.png", sector: "Oil & Gas PSU" },
  { name: "National Institute of Technology", short: "NIT", logo: "/assets/customers/NIT.png", sector: "Education" },
  { name: "NITTTR", short: "NITTTR", logo: "/assets/customers/nitttr.png", sector: "Education" },
  { name: "Indian Oil Corporation Limited", short: "IOCL", logo: "/assets/customers/IOCL.png", sector: "Oil & Gas PSU" },
  { name: "Bharat Petroleum Corporation Limited", short: "BPCL", logo: "/assets/customers/BPCL.png", sector: "Oil & Gas PSU" },
  { name: "Power Grid Corporation of India", short: "Powergrid", logo: "/assets/customers/Powergrid.jpg", sector: "Power Transmission" },
  { name: "SASTRA University", short: "SASTRA", logo: "/assets/customers/sastra university.png", sector: "Education" },
  { name: "Periyar Maniammai Institute of Science & Technology", short: "PMIST", logo: "/assets/customers/Periyar_Maniammai_Institute_of_Science_&_Technology_logo.png", sector: "Education" },
  { name: "Oil and Natural Gas Corporation", short: "ONGC", logo: "/assets/customers/ONGC.webp", sector: "Oil & Gas PSU" },
  { name: "Kerala Electrical & Allied Engg. Co. Ltd.", short: "KEL", logo: "/assets/customers/kerala-electrical.png", sector: "Govt. of Kerala Undertaking" },
  { name: "NLC India — Creating Wealth for Wellbeing", short: "NLC India", logo: "/assets/customers/create-wealth.png", sector: "Power PSU" },
  { name: "NTPL", short: "NTPL", logo: "/assets/customers/ntpl.png", sector: "Power Generation" },
  { name: "Tuticorin Thermal Power Station", short: "TTPS", logo: "/assets/customers/TTPS.png", sector: "Power Generation" },
  { name: "Indian Maritime University", short: "IMU", logo: "/assets/customers/IMU.png", sector: "Education" },
  { name: "IL&FS", short: "IL&FS", logo: "/assets/customers/ilfs.jpeg", sector: "Infrastructure" },
  { name: "Kothari Sugars & Chemicals Ltd.", short: "Kothari", logo: "/assets/customers/kothari.png", sector: "Sugar & Chemicals" },
  { name: "Central Asia Cement", short: "Central Asia Cement", logo: "/assets/customers/central-asia-cement.jpg", sector: "Cement" },
  { name: "ITC Cement", short: "IT Cem", logo: "/assets/customers/itc.jpg", sector: "Cement" },
  { name: "Ministry of Food Processing Industries", short: "MOFPI", logo: "/assets/customers/mofpi.png", sector: "Govt. of India" },
  { name: "NIFTEM-K", short: "NIFTEM-K", logo: "/assets/customers/niftem-k.jpg", sector: "Institute, Govt. of India" },
  { name: "KMC Hospital", short: "KMC", logo: "/assets/customers/KMC hospital.png", sector: "Healthcare" },
  { name: "Kanam", short: "Kanam", logo: "/assets/customers/kanam.png", sector: "Industrial" },
  { name: "NTPC Limited", short: "NTPC", logo: "/assets/customers/ntpc.jpg", sector: "Power Generation" },
];

export function byCat(slug: string): Product[] {
  return products.filter(p => p.cat === slug);
}

export function getProduct(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getCategory(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug);
}
